name: Build 

on: [push, pull_request]

jobs:
  armv7_job:
    runs-on: ubuntu-latest
    name: Build armv7
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Run commands
        id: runcmd
        with:
          arch: armv7
          distro: buster
          # Set an output parameter `uname` for use in subsequent steps
          run: |
            .configure
            make
