name: Build 

on: [push, pull_request]

jobs:
  armv7_job:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - arch: armv7
            distro: stretch
          - arch: armv6
            distro: stretch
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Run commands
        id: runcmd
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          # Not required, but speeds up builds
          githubToken: ${{ github.token }}  
          setup: |
            mkdir -p "${PWD}/artifacts"  
            
          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"

          # Pass some environment variables to the container
          env: | # YAML, but pipe character is necessary
            artifact_name: wmbusmeters-${{ matrix.distro }}_${{ matrix.arch }}
            
          # Set an output parameter `uname` for use in subsequent steps
          install: |
            apt-get update -q -y
            apt-get install -q -y build-essential librtlsdr-dev libusb-dev libncurses-dev checkinstall
            
          run: |
            pwd
            ls -la
            ./configure
            make
            checkinstall -y --install=no --pkgversion 1
            ls -la
            cp *.deb "/artifacts/"
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.distro }}_${{ matrix.arch }}
          path: artifacts/*.deb
 
